log_out = ['e:\\program files (x86)\\adobe\\acrobat 11.0\\setup files\\{ac76ba86-1033-ffff-7760-000000000006}\\windowsinstaller-kb893803-v2-x86.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\setup files\\{ac76ba86-1033-ffff-7760-000000000006}\\setup.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\pdfmaker\\office\\html2pdfwrapfor64bit.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\formscentral\\formscentralforacrobat.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\formscentral\\adobe air\\versions\\1.0\\resources\\captiveappentry.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\formscentral\\acrobatlauncher\\acrobatlauncher.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\xtras\\adobepdf\\printinf64.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\wow_helper.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\plug_ins\\scan\\acroscanbroker.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\plug_ins\\pi_brokers\\64bitmapibroker.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\logtransport2.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\arh.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\adobecollabsync.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrotray.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrotextextractor.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrord32.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrodist.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrobroker.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrobatinfo.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrobat_sl.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat\\acrobat.exe'
'e:\\program files (x86)\\adobe\\acrobat 11.0\\acrobat elements\\acrobat elements.exe'
'd:\\program\\autodesk\\autocad 2015\\styshwiz.exe'
'd:\\program\\autodesk\\autocad 2015\\styexe.exe'
'd:\\program\\autodesk\\autocad 2015\\slidelib.exe'
'd:\\program\\autodesk\\autocad 2015\\senddmp.exe'
'd:\\program\\autodesk\\autocad 2015\\pc3exe.exe'
'd:\\program\\autodesk\\autocad 2015\\inventor server\\bin\\registerinventorserver.exe'
'd:\\program\\autodesk\\autocad 2015\\inventor server\\bin\\inventorviewcompute.exe'
'd:\\program\\autodesk\\autocad 2015\\inventor server\\bin\\dwfbridge.exe'
'd:\\program\\autodesk\\autocad 2015\\inventor server\\bin\\bin32\\server32bithost.exe'
'd:\\program\\autodesk\\autocad 2015\\inventor server\\bin\\acivserverhost.exe'
'd:\\program\\autodesk\\autocad 2015\\hpsetup.exe'
'd:\\program\\autodesk\\autocad 2015\\dwgcheckstandards.exe'
'd:\\program\\autodesk\\autocad 2015\\dwg2spd.exe'
'd:\\program\\autodesk\\autocad 2015\\adsubaware.exe'
'd:\\program\\autodesk\\autocad 2015\\adrefman.exe'
'd:\\program\\autodesk\\autocad 2015\\admigrator.exe'
'd:\\program\\autodesk\\autocad 2015\\adflashvideoplayer.exe'
'd:\\program\\autodesk\\autocad 2015\\addplwiz.exe'
'd:\\program\\autodesk\\autocad 2015\\adcadmn.exe'
'd:\\program\\autodesk\\autocad 2015\\acwebbrowser\\acwebbrowser.exe'
'd:\\program\\autodesk\\autocad 2015\\actranslators.exe'
'd:\\program\\autodesk\\autocad 2015\\acsignapply.exe'
'd:\\program\\autodesk\\autocad 2015\\acsettingsync.exe'
'd:\\program\\autodesk\\autocad 2015\\accoreconsole.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\tools\\poolmigr.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\tools\\genzip.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\sys\\ge_zipdcl32.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\sys\\g3vved.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\setup\\en-us\\setup\\setup\\senddmp.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\setup\\en-us\\setup\\setup\\acdeltree.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\setup\\en-us\\setup\\setup.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\migration\\amdwgmigr19.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\gen\\genmsked.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\enu\\symbbautoreg.exe'
'd:\\program\\autodesk\\autocad 2015\\acadm\\acmpmdb32.exe'
'd:\\program\\autodesk\\autocad 2015\\acad.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\required\\adobeqtserver.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\pproheadless.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\photoshopserver.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\mpeghdvexport.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\logtransport2.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\gpusniffer.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\dvaaudiofilterscan.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\cephtmlengine\\cephtmlengine.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\anywhererenderer.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\anywhereproductionconverter.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\anywhereingest.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\anywhereencoder.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\adobe premiere pro.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\32\\importerredserver.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\32\\dynamiclinkmanager.exe'
'd:\\program\\adobe\\adobe premiere pro cc 2015\\32\\adobe qt32 server.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\sniffer.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\plug-ins\\spaces\\adobe spaces helper.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\linguistics\\userdictionarymigrationtool\\udmt.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\dynamiclinkmediaserver\\dynamiclinkmediaserver.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\dynamiclinkmediaserver\\amecommand.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\dynamiclinkmediaserver\\32\\importerredserver.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\dynamiclinkmediaserver\\32\\dynamiclinkmanager.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\dynamiclinkmediaserver\\32\\adobe qt32 server.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\droplet template.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\required\\cep\\cephtmlengine\\cephtmlengine.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\pngquant.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\photoshopprefsmanager.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\photoshop.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\node.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\logtransport2.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\convert.exe'
'd:\\program\\adobe\\adobe photoshop cc 2015\\agf3dprinterdriver.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\required\\adobeqtserver.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\photoshopserver.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\logtransport2.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\arh.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\adobe media encoder.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\32\\importerredserver.exe'
'd:\\program\\adobe\\adobe media encoder cs6\\32\\adobe qt32 server.exe'
'd:\\program\\adobe\\adobe illustrator cc 2015\\support files\\contents\\windows\\logtransport2.exe'
'd:\\program\\adobe\\adobe illustrator cc 2015\\support files\\contents\\windows\\illustrator.exe'
'd:\\program\\adobe\\adobe illustrator cc 2015\\support files\\contents\\windows\\cephtmlengine\\cephtmlengine.exe'
'd:\\program\\adobe\\adobe illustrator cc 2015\\support files\\contents\\windows\\aisafemodelauncher.exe'
'd:\\program\\adobe\\adobe illustrator cc 2015\\support files\\contents\\windows\\aigpusniffer.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\videopublisher.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\utils\\opt\\win\\pngquant.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\swf_components\\ws\\civetweb.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\swf_components\\alternatereporting\\alternatereporting.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\pptxtest.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\logtransport2.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\unpack200.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\tnameserv.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\ssvagent.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\servertool.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\rmiregistry.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\rmid.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\policytool.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\pack200.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\orbd.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\ktab.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\klist.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\kinit.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\keytool.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\jp2launcher.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\jjs.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\javaws.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\javaw.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\javacpl.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\java.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\java-rmi.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm\\bin\\jabswitch.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\unpack200.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\tnameserv.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\ssvagent.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\servertool.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\rmiregistry.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\rmid.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\policytool.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\pack200.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\orbd.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\ktab.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\klist.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\kinit.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\keytool.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\jp2launcher.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\jjs.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\javaws.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\javaw.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\javacpl.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\java.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\java-rmi.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\jvm32\\bin\\jabswitch.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\cpcefhelper.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\ckmondpi\\ckmondpi.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\arh.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\aggregator.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\adobecaptivateforwindowsstoreapp.exe'
'd:\\program\\adobe\\adobe captivate 9 x64\\adobecaptivate.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\share on soundcloud.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\logtransport2.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\gpusniffer.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\dvaaudiofilterscan.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\adobe audition cc.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\32\\importerredserver.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\32\\dynamiclinkmanager.exe'
'd:\\program\\adobe\\adobe audition cc 2015\\32\\adobe qt32 server.exe'
'c:\\windows\\solidworks\\im_20140-40000-1100-100\\sldim\\swhelpviewer\\swhelpviewer.exe'
'c:\\windows\\solidworks\\im_20140-40000-1100-100\\sldim\\sldim.exe'
'c:\\windows\\solidworks\\im_20140-40000-1100-100\\sldim\\sldadminoptioneditor.exe'
'c:\\windows\\solidworks\\im_20140-40000-1100-100\\sldim\\regval.exe'
'c:\\windows\\solidworks\\im_20140-40000-1100-100\\setup.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\removeadappmgr.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\cer\\senddmp.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\adsdscheck.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\adappmgrtaskclean.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\adappmgrsvcaclreset.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\adappmgrsvc.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\adappmgrshortcut.exe'
'c:\\users\\administrator\\appdata\\local\\autodesk\\.adskappmanager\\r1\\adappmgr.exe'
'c:\\programdata\\autodesk\\applicationplugins\\autodesk importskp.bundle\\contents\\windows\\2015\\converter\\sketchupconverter.exe'
'c:\\programdata\\autodesk\\applicationplugins\\autodesk importskp.bundle\\contents\\windows\\2014\\converter\\sketchupconverter.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\13756\\readerupdater.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\13756\\adobearmhelper.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\13756\\adobearm.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\13756\\acrobatupdater.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\104\\readerupdater.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\104\\adobearmhelper.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\104\\adobearm.exe'
'c:\\programdata\\adobe\\arm\\acrobat_11.0.00\\104\\acrobatupdater.exe'
'c:\\program files\\solidworks corp\\solidworks\\utlreportviewer.exe'
'c:\\program files\\solidworks corp\\solidworks\\toolbox\\toolboxconfigure\\sldtoolboxupdater.exe'
'c:\\program files\\solidworks corp\\solidworks\\toolbox\\toolboxconfigure\\sldtoolboxconfigure.exe'
'c:\\program files\\solidworks corp\\solidworks\\toolbox\\data utilities\\updatebrowserdata.exe'
'c:\\program files\\solidworks corp\\solidworks\\toolbox\\data utilities\\sldsetdocprop.exe'
'c:\\program files\\solidworks corp\\solidworks\\swvbaserver\\swvbaserver.exe'
'c:\\program files\\solidworks corp\\solidworks\\swvbaserver\\drawcompare.exe'
'c:\\program files\\solidworks corp\\solidworks\\swspmanager.exe'
'c:\\program files\\solidworks corp\\solidworks\\swshellfilelauncher.exe'
'c:\\program files\\solidworks corp\\solidworks\\swscheduler\\swscheduler.exe'
'c:\\program files\\solidworks corp\\solidworks\\swscheduler\\swboengine.exe'
'c:\\program files\\solidworks corp\\solidworks\\swscheduler\\dtsservicemanager.exe'
'c:\\program files\\solidworks corp\\solidworks\\swscheduler\\dtsmonitor.exe'
'c:\\program files\\solidworks corp\\solidworks\\swscheduler\\dtscoordinatorservice.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldworks_fs.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldworks.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldutils\\gtreportmanager.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldu3d.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldshellextserver.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldrx\\sldrxmm.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldrx\\sldrx.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldpropertytabbuilder\\propertytabbuilder.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldprocmon.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldphotoshopcon.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldexitapp.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldcostingtemplateeditorappu.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldbgproc.exe'
'c:\\program files\\solidworks corp\\solidworks\\sldbenchmarking\\sldbenchmark.exe'
'c:\\program files\\solidworks corp\\solidworks\\sld3dviauploader\\sld3dviauploader.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\utilities\\simulation cleaning utility.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\utilities\\material.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\utilities\\cosmossupporttool.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\stres.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\stopt.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\star.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\setup\\i386\\swlicservinst.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\setup\\i386\\swactwiz.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\renum.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\pre1.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\postans.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\pat2cos.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\parametricobject.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\nstar.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\nas2cos.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\license\\setup\\i386\\swlicservinst.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\license\\setup\\i386\\swactwiz.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\ids2cos.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\hstar.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\ghs3dv3.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\ghs3d.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\fat.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\dstar.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\dpost.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cwmeshproc.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cwanalysisproc.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cos2xds.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cos2pat.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cos2nas.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cos2ans.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\cos2abq.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\check.exe'
'c:\\program files\\solidworks corp\\solidworks\\simulation\\ans2cos.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\x86\\swlicservinst.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\x86\\swinstactsvc.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swlmwiz.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swlmutil.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swlicservinst.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swinstactsvc.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swactwizhelpersc.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swactwiz_s.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\swactwiz.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\migratedesignlib.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\lmutil.exe'
'c:\\program files\\solidworks corp\\solidworks\\setup\\i386\\copyoptwiz.exe'
'c:\\program files\\solidworks corp\\solidworks\\setcatenv.exe'
'c:\\program files\\solidworks corp\\solidworks\\rtlibrarymanager.exe'
'c:\\program files\\solidworks corp\\solidworks\\propertymanagerupload.exe'
'c:\\program files\\solidworks corp\\solidworks\\photoview\\photoview360_cl.exe'
'c:\\program files\\solidworks corp\\solidworks\\photoview\\photoview360.exe'
'c:\\program files\\solidworks corp\\solidworks\\localsldservice.exe'
'c:\\program files\\solidworks corp\\solidworks\\gabiswengine.exe'
'c:\\program files\\solidworks corp\\solidworks\\floxpress\\bin\\efdsolver.exe'
'c:\\program files\\solidworks corp\\solidworks\\dsgnchkrptview.exe'
'c:\\program files\\solidworks corp\\solidworks\\dsgnchk\\dsgnchkdesignbinderu.exe'
'c:\\program files\\solidworks corp\\solidworks\\dsgnchk\\dsgnchkbldu.exe'
'c:\\program files\\solidworks corp\\solidworks\\driveworksxpress\\driveworksxpressdt.exe'
'c:\\program files\\solidworks corp\\solidworks\\circuitworksfull\\circuitworks.exe'
'c:\\program files\\solidworks corp\\solidworks\\brazil\\brazilrender.exe'
'c:\\program files\\solidworks corp\\solidworks\\api\\pidcollector.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\e-style\\warp.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\e-style\\pipe.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\e-style\\packw.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\e-style\\cool.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\c-style\\warp.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\c-style\\pipe.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\c-style\\packw.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\c-style\\cool.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\weld\\weldx64.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\warps3d.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\warp.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\runnerbalance\\runnerbalance.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\pipe.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\packw.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\cool.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\cgltks\\cgltks.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\software\\b-style\\cgltks\\bthickcal.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\simpoewrapperx64.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\simpoeservicesw.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\simpoeemptyexe.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\powerpointreport.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\html2word.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\dbconverter.exe'
'c:\\program files\\solidworks corp\\solidworks plastics\\simpoemv\\checkverinfo_swp.exe']

f = 'c:\\program files (x86)\\adobe\\adobe captivate quiz results analyzer 9\\adobe captivate quiz results analyzer 9.exe'

if __name__ == '__main__':
    print(f in log_out)
    